homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    # Pages Index root
    path('', views.HomepageView.as_view(), name='homepage'),

    # register root
    path('register/', views.register, name='register'),

    # login root
    path('login/', views.login, name='login'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # homepage root
    path('', include('homepage.urls')),
    # login root
    path('registration/', include('registration.urls')),
    # Polls root
    path('polls/', include('polls.urls')),
    # Admin Panel root
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # Pages Index root
    path('', views.IndexView.as_view(), name='index'),
    # Pages Detail root
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # Pages Results root
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # Vote root
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'
urlpatterns = [
    # Pages Login root
    path('', views.RegistrationView.as_view(), name='login'),

]

homepage/models.py
from django.db import models

class User(models.Model):
    prenom = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

polls/models.py
# Import Modules
import datetime

from django.db import models
from django.utils import timezone

#
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

homepage/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import User


class HomepageView(generic.ListView):
    template_name = 'homepage/homepage.html'

    # In case we define a comportment in the homepage linked with a DATABASE we have to set this function
    def get_queryset(self):
        """

        """
        return


# Vote contain paramaters that link with the question ID
def register(request):
    if request.method == 'GET':
        # récupère les données saisies par l'utilisateur
        prenom = request.GET['prenom']
        email = request.GET['email']
        password = request.GET['password']

        # Vérifie que l'émail n'exite pas.
        # hasher le mot de pass
        # ajoute un enregistrement dans la base de données
        p = User(prenom=prenom, email=email, password=password)
        p.save()

        # renvoyer un message à l'utilisateur
        return render(request, 'homepage/register.html',{'message':'Merci ' + prenom + ' de vous être enregistrer '})
    else:
        return render(request, 'homepage/register.html',{'message':'erreur'})


# Vote contain paramaters that link with the question ID
def login(request):
    if request.method == 'GET':
        # récupère les données saisies par l'utilisateur
        email = request.GET['email']
        # vérifier la validité du password
        password = request.GET['password']

        # ouvrir la base et rechercher l'email
        # User.objects.get(email=email)
        # User.objects.filter(email=email)
        if User.objects.filter(email=email):
            # renvoyer un message à l'utilisateur
            return render(request, 'homepage/profil.html',{'message': ''})
        else:
            return render(request, 'homepage/homepage.html',{'error_message':'Vous devez vous inscrire'})
    else:
        return render(request, 'homepage/register.html',{'error_message':'erreur de connexion'})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

# Generic View Index ( a view called from a class where we define a template_name then call it in a root patterns )

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

# Generic View Detail ( a view called from a class where we define a template_name then call it in a root patterns )
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

# Generic View Restults ( a view called from a class where we define a template_name then call it in a root patterns )
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# Vote contain paramaters that link with the question ID
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

homepage/templates/homepage/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}">
    <title>Title</title>
</head>
<body>
    <h2>Bienvenue dans notre équipe</h2>
	{{ error_message }}
<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form action="{% url 'homepage:register' %}" method="get">
            {% csrf_token %}
			<h1>Créer un compte🖊</h1>
			<div class="social-container">
			</div>
			<span></span>
			<input type="text" name="prenom" placeholder="Prénom" />
			<input type="email" name="email" placeholder="Email" />
			<input type="password" name="password" placeholder="Mot de passe" />
			<!-- <input class="button" type="submit" value="login"> -->
			<button>S'inscrire</button>
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form action="{% url 'homepage:login' %}" method="get">
            {% csrf_token %}
			<h1>Connexion</h1>
			<div class="social-container">
			
			</div>
			<span>Utilisez votre compte</span>
			<input type="email" name="email" placeholder="Email" />
			<input type="password" name="password" placeholder="Mot de passe" />
			<a href="#">Mot de passe oublié?</a>
			<button>Connexion</button>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
            <h1>😊</h1>
				<h1>Content de te revoir!</h1>
				<p>Pour rester connecté avec nous, veuillez vous connecter avec vos informations personnelles</p>
				<button class="ghost" id="signIn">Connexion</button>
			</div>
			<div class="overlay-panel overlay-right">
            <h1>👋</h1>
				<h1>Salut les amis!</h1>
				<p>Entrez vos informations personnelles et commencez votre voyage avec nous</p>
				<button class="ghost" id="signUp">S'inscrire</button>
			</div>
		</div>
	</div>
</div>

</footer>
</body>
</html>
<script>
const signUpButton = document.getElementById('signUp');
const signInButton = document.getElementById('signIn');
const container = document.getElementById('container');

signUpButton.addEventListener('click', () => {
	container.classList.add("right-panel-active");
});

signInButton.addEventListener('click', () => {
	container.classList.remove("right-panel-active");
});
</script>

homepage/templates/homepage/login.html
{{message}}

homepage/templates/homepage/profil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/profil.css' %}">
    <title>Title</title>
</head>
<body>
<h1>Profile </h1>
<button> déconnexion </button>
<button> Edition de profile </button>
<div class="tabset">
  <!-- Tab 1 -->
  <input type="radio" name="tabset" id="tab1" aria-controls="marzen" checked>
  <label for="tab1">Aime</label>
  <!-- Tab 2 -->
  <input type="radio" name="tabset" id="tab2" aria-controls="rauchbier">
  <label for="tab2">Aime pas</label>
  <!-- Tab 3 -->
  <input type="radio" name="tabset" id="tab3" aria-controls="dunkles">
  <label for="tab3">Comentaire</label>
  
  <div class="tab-panels">
    <section id="marzen" class="tab-panel">
      <strong>Dit nous ce que vous avez aimé cette semaine</strong> <br>
      <input></input> <br>
      <input></input> <br> <br>
      <button>validé</button>
   
  </section>
    <section id="rauchbier" class="tab-panel">
     <strong>Dit nous ce que vous avez pas aimé cette semaine</strong> <br>
      <input></input> <br>
     <input></input> <br>
      <input></input> <br> <br>
      <button>validé</button>
    </section>
    <section id="dunkles" class="tab-panel">
      <strong>Tout les commantaires:</strong>
    </section>
  </div>
  
</div>
</body>
</html>

homepage/templates/homepage/register.html
{{message}}

 

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>